# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    container:
      image: python:${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir --requirement requirements.lint.txt
      - name: Check version
        run: |
          which python
          python --version
          which pflake8
          pflake8 --version
          which mypy
          mypy --version
      - name: Lint python sources
        run: |
          pflake8 --verbose --count --show-source --statistics
