
name: Pytest

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pytest_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openmodelica-version: ['1.13.0']

    name: A job to run pytest
    steps:
      - uses: actions/checkout@v2
      - name: Docker
        uses: ./.github/actions/pytest
        with:
          openmodelica-version: ${{ matrix.openmodelica-version }}
