
name: Pytest omc (1.14.2)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pytest_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker
        uses: ./.github/actions/pytest-omc1.14.2
