
name: Pytest

on:
  # Runs on pushes targeting the master, develop branch
  push:
    branches: [ master, develop ]
  # Runs on pull-request targeting the master, develop branch
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # NOTE: update to latest
          - openmodelica: "1.22.0"
            python: "3.12"
          # - openmodelica: "1.22.0"
          #   python: "3.11"
          # - openmodelica: "1.22.0"
          #   python: "3.10"
          # - openmodelica: "1.22.0"
          #   python: "3.9"
          # - openmodelica: "1.22.0"
          #   python: "3.8"

          # - openmodelica: "1.21.0"
          #   python: "3.12"
          # - openmodelica: "1.21.0"
          #   python: "3.8"
          # - openmodelica: "1.20.0"
          #   python: "3.12"
          # - openmodelica: "1.20.0"
          #   python: "3.8"
          # - openmodelica: "1.19.2"
          #   python: "3.12"
          # - openmodelica: "1.19.2"
          #   python: "3.8"
          # - openmodelica: "1.18.0"
          #   python: "3.12"
          # - openmodelica: "1.18.0"
          #   python: "3.8"
          # - openmodelica: "1.17.0"
          #   python: "3.12"
          # - openmodelica: "1.17.0"
          #   python: "3.8"
          # - openmodelica: "1.16.2"
          #   python: "3.12"
          # - openmodelica: "1.16.2"
          #   python: "3.8"
          # - openmodelica: "1.14.2"
          #   python: "3.12"
          # - openmodelica: "1.14.2"
          #   python: "3.8"
          # - openmodelica: "1.13.2"
          #   python: "3.12"
          # - openmodelica: "1.13.2"
          #   python: "3.8"

    container:
      image: ijknabla/openmodelica:v${{ matrix.openmodelica }}-python${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          ln -s /usr/local/bin/python${{ matrix.python }} /usr/local/bin/python
          python -m pip install -U pip poetry
          python -m pip install ./
          python -m poetry export --only=test | python -m pip install -r /dev/stdin
      - name: Check version
        run: |
          omc --version
          python --version
          python -m pytest --version
      - name: Test python code
        run: |
          sudo -u user python .github/pretest.py
          sudo -u user python -m pytest -v
