
name: Pytest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - omc-version: 1.13.0
            python-version: 3.6
            os: stretch
    container:
      image: ijknabla/openmodelica-python3:omc${{ matrix.omc-version }}-py${{ matrix.python-version }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Check version
        run: |
          which omc
          omc --version
          which python
          python --version
