
name: Pytest

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - omc-version: omc1.13
            python-version: py3.6
            os: stretch
          - omc-version: omc1.14
            python-version: py3.6
            os: buster
          - omc-version: omc1.14
            python-version: py3.9
            os: buster
          - omc-version: omc1.16
            python-version: py3.6
            os: buster
          - omc-version: omc1.16
            python-version: py3.9
            os: buster
          - omc-version: omc1.17
            python-version: py3.6
            os: buster
          - omc-version: omc1.17
            python-version: py3.9
            os: buster
          - omc-version: omc1.18
            python-version: py3.6
            os: bullseye
          - omc-version: omc1.18
            python-version: py3.9
            os: bullseye
          - omc-version: omc1.19
            python-version: py3.6
            os: bullseye
          - omc-version: omc1.19
            python-version: py3.9
            os: bullseye
          - omc-version: omc1.20
            python-version: py3.6
            os: bullseye
          - omc-version: omc1.20
            python-version: py3.9
            os: bullseye
    container:
      image: ijknabla/openmodelica-python3:${{ matrix.omc-version }}-${{ matrix.python-version }}-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo -u user pip install --no-cache-dir --upgrade pip
          sudo -u user pip install --no-cache-dir --requirement requirements.test.txt
      - name: Check version
        run: |
          sudo -u user which omc
          sudo -u user omc --version
          sudo -u user which python
          sudo -u user python --version
          sudo -u user python -m pytest --version
      - name: Test python sources
        run: |
          sudo -u user python -m pytest -v tests/
